# Generated by Django 3.1.7 on 2021-04-23 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2021, 4, 23, 9, 6, 41, 97988))),
                ('img', models.ImageField(blank=True, upload_to='medias')),
                ('medias', models.ManyToManyField(to='medias.Media')),
            ],
        ),
    ]
